/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.table.DefaultTableModel;
import db.Koneksi;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

public class AdminDashboardForm extends javax.swing.JFrame {

    private void loadStatistikKamarTersedia() {
    try {
        String sql = "SELECT COUNT(*) AS jumlah FROM kamar WHERE status = 'Tersedia'";
        java.sql.Connection conn = Koneksi.configDB();
        java.sql.Statement stm = conn.createStatement();
        java.sql.ResultSet res = stm.executeQuery(sql);
        if (res.next()) {
            lblAngkaKamarTersedia.setText(res.getString("jumlah"));
        }
        lblTeksKamarTersedia.setText("Kamar Tersedia");
    } catch (Exception e) {
        lblAngkaKamarTersedia.setText("N/A");
    }
}

// Method untuk mengambil data jumlah kamar dipesan
private void loadStatistikKamarDipesan() {
    try {
        String sql = "SELECT COUNT(*) AS jumlah FROM kamar WHERE status = 'Dipesan'";
        java.sql.Connection conn = Koneksi.configDB();
        java.sql.Statement stm = conn.createStatement();
        java.sql.ResultSet res = stm.executeQuery(sql);
        if (res.next()) {
            lblAngkaKamarDipesan.setText(res.getString("jumlah"));
        }
        lblTeksKamarDipesan.setText("Kamar Dipesan");
    } catch (Exception e) {
        lblAngkaKamarDipesan.setText("N/A");
    }
}
private void loadTabelReservasi() {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("ID Pesanan");
    model.addColumn("Nama Tamu");
    model.addColumn("Tipe Kamar");
    model.addColumn("Tgl Check-in");

    try {
        String sql = "SELECT p.id, u.nama_lengkap, tk.nama_tipe, p.tanggal_checkin "
                   + "FROM pemesanan p "
                   + "JOIN users u ON p.id_user = u.id "
                   + "JOIN kamar k ON p.id_kamar = k.id "
                   + "JOIN tipe_kamar tk ON k.id_tipe_kamar = tk.id "
                   + "ORDER BY p.id DESC LIMIT 5";
        
        java.sql.Connection conn = Koneksi.configDB();
        java.sql.Statement stm = conn.createStatement();
        java.sql.ResultSet res = stm.executeQuery(sql);
        
        while(res.next()){
            model.addRow(new Object[]{
                "P00" + res.getString("p.id"),
                res.getString("u.nama_lengkap"),
                res.getString("tk.nama_tipe"),
                res.getString("p.tanggal_checkin")
            });
        }
        tabelReservasiTerbaru.setModel(model);
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal memuat tabel reservasi: " + e.getMessage());
    }
}
private void loadStatistikTipeKamar() {
    try {
        String sql = "SELECT COUNT(*) AS jumlah FROM tipe_kamar";
        java.sql.Connection conn = Koneksi.configDB();
        java.sql.Statement stm = conn.createStatement();
        java.sql.ResultSet res = stm.executeQuery(sql);
        if (res.next()) {
            lblAngkaTipeKamar.setText(res.getString("jumlah"));
        }
        lblTeksTipeKamar.setText("Tipe Kamar Aktif");
    } catch (Exception e) {
        lblAngkaTipeKamar.setText("N/A");
    }
}

// Method untuk mengambil data total reservasi
private void loadStatistikTotalReservasi() {
    try {
        String sql = "SELECT COUNT(*) AS jumlah FROM pemesanan WHERE MONTH(tanggal_checkin) = MONTH(CURRENT_DATE()) AND YEAR(tanggal_checkin) = YEAR(CURRENT_DATE())";
        
        java.sql.Connection conn = Koneksi.configDB();
        java.sql.Statement stm = conn.createStatement();
        java.sql.ResultSet res = stm.executeQuery(sql);
        if (res.next()) {
            lblAngkaTotalReservasi.setText(res.getString("jumlah"));
        }
        lblTeksTotalReservasi.setText("Check-in Bulan Ini"); 
    } catch (Exception e) {
        lblAngkaTotalReservasi.setText("N/A");
    }
}
    public AdminDashboardForm() {
        initComponents();
        //metode untuk memuat data dari database
        loadStatistikKamarTersedia();
        loadStatistikKamarDipesan();
        loadTabelReservasi();
        loadStatistikTipeKamar();      
        loadStatistikTotalReservasi();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        panelNavigasi = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        ManajemenKamarForm = new javax.swing.JButton();
        panelKonten = new javax.swing.JPanel();
        panelStatistik = new javax.swing.JPanel();
        kartuStat1 = new javax.swing.JPanel();
        lblAngkaKamarTersedia = new javax.swing.JLabel();
        lblTeksKamarTersedia = new javax.swing.JLabel();
        kartuStat2 = new javax.swing.JPanel();
        lblAngkaKamarDipesan = new javax.swing.JLabel();
        lblTeksKamarDipesan = new javax.swing.JLabel();
        kartuStat3 = new javax.swing.JPanel();
        lblAngkaTipeKamar = new javax.swing.JLabel();
        lblTeksTipeKamar = new javax.swing.JLabel();
        kartuStat4 = new javax.swing.JPanel();
        lblAngkaTotalReservasi = new javax.swing.JLabel();
        lblTeksTotalReservasi = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelReservasiTerbaru = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dashboard - Hotel Surya Indah Salatiga");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Hotel Surya Indah Salatiga");
        jLabel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Selamat Datang, Admin");

        panelNavigasi.setBackground(new java.awt.Color(0, 51, 102));
        panelNavigasi.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15));
        panelNavigasi.setPreferredSize(new java.awt.Dimension(220, 100));

        jButton1.setBackground(new java.awt.Color(0, 71, 132));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Dashboard");

        jButton2.setBackground(new java.awt.Color(0, 71, 132));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Logout");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 71, 132));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Manajemen User ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 71, 132));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Laporan ");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(0, 71, 132));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Tipe Kamar ");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(0, 71, 132));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Data Reservasi");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        ManajemenKamarForm.setBackground(new java.awt.Color(0, 71, 132));
        ManajemenKamarForm.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ManajemenKamarForm.setForeground(new java.awt.Color(255, 255, 255));
        ManajemenKamarForm.setText("Manajemen Kamar ");
        ManajemenKamarForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManajemenKamarFormActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelNavigasiLayout = new javax.swing.GroupLayout(panelNavigasi);
        panelNavigasi.setLayout(panelNavigasiLayout);
        panelNavigasiLayout.setHorizontalGroup(
            panelNavigasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNavigasiLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(panelNavigasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ManajemenKamarForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        panelNavigasiLayout.setVerticalGroup(
            panelNavigasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNavigasiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(ManajemenKamarForm)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addGap(18, 18, 18)
                .addComponent(jButton6)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 415, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(29, 29, 29))
        );

        panelStatistik.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));

        kartuStat1.setBackground(new java.awt.Color(255, 255, 255));
        kartuStat1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        lblAngkaKamarTersedia.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblAngkaKamarTersedia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAngkaKamarTersedia.setText("0");

        lblTeksKamarTersedia.setText("Kamar Tersedia");

        javax.swing.GroupLayout kartuStat1Layout = new javax.swing.GroupLayout(kartuStat1);
        kartuStat1.setLayout(kartuStat1Layout);
        kartuStat1Layout.setHorizontalGroup(
            kartuStat1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kartuStat1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAngkaKamarTersedia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kartuStat1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTeksKamarTersedia, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );
        kartuStat1Layout.setVerticalGroup(
            kartuStat1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kartuStat1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblAngkaKamarTersedia)
                .addGap(18, 18, 18)
                .addComponent(lblTeksKamarTersedia)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        kartuStat2.setBackground(new java.awt.Color(255, 255, 255));
        kartuStat2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        lblAngkaKamarDipesan.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblAngkaKamarDipesan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAngkaKamarDipesan.setText("0");

        lblTeksKamarDipesan.setText("Kamar Dipesan");

        javax.swing.GroupLayout kartuStat2Layout = new javax.swing.GroupLayout(kartuStat2);
        kartuStat2.setLayout(kartuStat2Layout);
        kartuStat2Layout.setHorizontalGroup(
            kartuStat2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kartuStat2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAngkaKamarDipesan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kartuStat2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTeksKamarDipesan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );
        kartuStat2Layout.setVerticalGroup(
            kartuStat2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kartuStat2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblAngkaKamarDipesan)
                .addGap(18, 18, 18)
                .addComponent(lblTeksKamarDipesan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        kartuStat3.setBackground(new java.awt.Color(255, 255, 255));
        kartuStat3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        lblAngkaTipeKamar.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblAngkaTipeKamar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAngkaTipeKamar.setText("0");

        lblTeksTipeKamar.setText("Kamar Aktif");

        javax.swing.GroupLayout kartuStat3Layout = new javax.swing.GroupLayout(kartuStat3);
        kartuStat3.setLayout(kartuStat3Layout);
        kartuStat3Layout.setHorizontalGroup(
            kartuStat3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kartuStat3Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(kartuStat3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kartuStat3Layout.createSequentialGroup()
                        .addComponent(lblAngkaTipeKamar, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kartuStat3Layout.createSequentialGroup()
                        .addComponent(lblTeksTipeKamar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54))))
        );
        kartuStat3Layout.setVerticalGroup(
            kartuStat3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kartuStat3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblAngkaTipeKamar)
                .addGap(18, 18, 18)
                .addComponent(lblTeksTipeKamar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        kartuStat4.setBackground(new java.awt.Color(255, 255, 255));
        kartuStat4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        lblAngkaTotalReservasi.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblAngkaTotalReservasi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAngkaTotalReservasi.setText("0");

        lblTeksTotalReservasi.setText("Check-in");

        javax.swing.GroupLayout kartuStat4Layout = new javax.swing.GroupLayout(kartuStat4);
        kartuStat4.setLayout(kartuStat4Layout);
        kartuStat4Layout.setHorizontalGroup(
            kartuStat4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kartuStat4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAngkaTotalReservasi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kartuStat4Layout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addComponent(lblTeksTotalReservasi, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );
        kartuStat4Layout.setVerticalGroup(
            kartuStat4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kartuStat4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblAngkaTotalReservasi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(lblTeksTotalReservasi)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelStatistikLayout = new javax.swing.GroupLayout(panelStatistik);
        panelStatistik.setLayout(panelStatistikLayout);
        panelStatistikLayout.setHorizontalGroup(
            panelStatistikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelStatistikLayout.createSequentialGroup()
                .addGroup(panelStatistikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(kartuStat1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kartuStat3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelStatistikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(kartuStat4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kartuStat2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        panelStatistikLayout.setVerticalGroup(
            panelStatistikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelStatistikLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelStatistikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kartuStat1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kartuStat2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(panelStatistikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(kartuStat3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kartuStat4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tabelReservasiTerbaru.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelReservasiTerbaru);

        javax.swing.GroupLayout panelKontenLayout = new javax.swing.GroupLayout(panelKonten);
        panelKonten.setLayout(panelKontenLayout);
        panelKontenLayout.setHorizontalGroup(
            panelKontenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKontenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelStatistik, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelKontenLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1049, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelKontenLayout.setVerticalGroup(
            panelKontenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKontenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelStatistik, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(47, 47, 47)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelNavigasi, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelKonten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(186, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelKonten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelNavigasi, javax.swing.GroupLayout.PREFERRED_SIZE, 759, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ManajemenKamarFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManajemenKamarFormActionPerformed
        new ManajemenKamarForm().setVisible(true);
    }//GEN-LAST:event_ManajemenKamarFormActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        new ManajemenTipeKamarForm().setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        new DataReservasiForm().setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        new LaporanForm().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new ManajemenUserForm().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this, 
        "Apakah Anda yakin ingin logout?", 
        "Konfirmasi Logout", 
        JOptionPane.YES_NO_OPTION);
        
        if (confirm == JOptionPane.YES_OPTION) {
        new LoginForm().setVisible(true);
        this.dispose();
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashboardForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashboardForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashboardForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashboardForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDashboardForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ManajemenKamarForm;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel kartuStat1;
    private javax.swing.JPanel kartuStat2;
    private javax.swing.JPanel kartuStat3;
    private javax.swing.JPanel kartuStat4;
    private javax.swing.JLabel lblAngkaKamarDipesan;
    private javax.swing.JLabel lblAngkaKamarTersedia;
    private javax.swing.JLabel lblAngkaTipeKamar;
    private javax.swing.JLabel lblAngkaTotalReservasi;
    private javax.swing.JLabel lblTeksKamarDipesan;
    private javax.swing.JLabel lblTeksKamarTersedia;
    private javax.swing.JLabel lblTeksTipeKamar;
    private javax.swing.JLabel lblTeksTotalReservasi;
    private javax.swing.JPanel panelKonten;
    private javax.swing.JPanel panelNavigasi;
    private javax.swing.JPanel panelStatistik;
    private javax.swing.JTable tabelReservasiTerbaru;
    // End of variables declaration//GEN-END:variables
}
