
package view;
import controller.ReservasiController;
import java.awt.Color;
import java.awt.Font;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Pemesanan;

public class DataReservasiForm extends javax.swing.JFrame {

    private final ReservasiController controller;
    
    public DataReservasiForm() {
        initComponents();
        this.controller = new ReservasiController();
        
        tabelReservasi.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 14));
        tabelReservasi.getTableHeader().setBackground(new Color(0, 51, 102));
        tabelReservasi.getTableHeader().setForeground(new Color(255, 255, 255));

        comboUpdateStatus.removeAllItems();
        comboUpdateStatus.addItem("Terkonfirmasi");
        comboUpdateStatus.addItem("Selesai");
        comboUpdateStatus.addItem("Dibatalkan");
        
        load_table();
        panelAksi.setVisible(false);
    }

    private void load_table() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("Nama Tamu");
        model.addColumn("No. Kamar");
        model.addColumn("Tipe Kamar");
        model.addColumn("Check-in");
        model.addColumn("Check-out");
        model.addColumn("Status");

        List<Pemesanan> listPemesanan = controller.getAllReservasi();
        for (Pemesanan p : listPemesanan) {
            model.addRow(new Object[]{
                p.getId(),
                p.getUser().getNamaLengkap(),
                p.getKamar().getNomorKamar(),
                p.getKamar().getTipeKamar().getNamaTipe(),
                p.getTanggalCheckin().toString(),
                p.getTanggalCheckout().toString(),
                p.getStatusPemesanan()
            });
        }
        tabelReservasi.setModel(model);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelJudul = new javax.swing.JPanel();
        lblJudulUtama = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelReservasi = new javax.swing.JTable();
        panelAksi = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblDetailId = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        comboUpdateStatus = new javax.swing.JComboBox<>();
        btnUpdateStatus = new javax.swing.JButton();
        btnHapusReservasi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Manajemen Data Reservasi - Hotel Surya Indah Salatiga");

        panelJudul.setBackground(new java.awt.Color(0, 51, 102));

        lblJudulUtama.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        lblJudulUtama.setForeground(new java.awt.Color(255, 255, 255));
        lblJudulUtama.setText("Manajemen Data Reservasi");

        javax.swing.GroupLayout panelJudulLayout = new javax.swing.GroupLayout(panelJudul);
        panelJudul.setLayout(panelJudulLayout);
        panelJudulLayout.setHorizontalGroup(
            panelJudulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelJudulLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblJudulUtama)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelJudulLayout.setVerticalGroup(
            panelJudulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelJudulLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lblJudulUtama)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        tabelReservasi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tabelReservasi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelReservasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelReservasiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelReservasi);

        jScrollPane2.setViewportView(jScrollPane1);

        panelAksi.setBackground(new java.awt.Color(255, 255, 255));
        panelAksi.setBorder(javax.swing.BorderFactory.createTitledBorder("Aksi untuk Data Terpilih"));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("ID Reservasi:");

        lblDetailId.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDetailId.setText("(ID)");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Ubah Status Ke:");

        comboUpdateStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnUpdateStatus.setText("Update Status");
        btnUpdateStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateStatusActionPerformed(evt);
            }
        });

        btnHapusReservasi.setBackground(new java.awt.Color(220, 53, 69));
        btnHapusReservasi.setForeground(new java.awt.Color(255, 255, 255));
        btnHapusReservasi.setText("Hapus");
        btnHapusReservasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusReservasiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAksiLayout = new javax.swing.GroupLayout(panelAksi);
        panelAksi.setLayout(panelAksiLayout);
        panelAksiLayout.setHorizontalGroup(
            panelAksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAksiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(lblDetailId, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(jLabel2)
                .addGap(50, 50, 50)
                .addComponent(comboUpdateStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addComponent(btnUpdateStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(btnHapusReservasi, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(619, Short.MAX_VALUE))
        );
        panelAksiLayout.setVerticalGroup(
            panelAksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAksiLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(panelAksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblDetailId)
                    .addComponent(jLabel2)
                    .addComponent(comboUpdateStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateStatus)
                    .addComponent(btnHapusReservasi))
                .addContainerGap(132, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelJudul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(panelAksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panelJudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelAksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabelReservasiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelReservasiMouseClicked
   panelAksi.setVisible(true);
    
        int baris = tabelReservasi.rowAtPoint(evt.getPoint());
        String idReservasi = tabelReservasi.getValueAt(baris, 0).toString();
        String statusSaatIni = tabelReservasi.getValueAt(baris, 6).toString();
        
        lblDetailId.setText(idReservasi);
        comboUpdateStatus.setSelectedItem(statusSaatIni);
    }//GEN-LAST:event_tabelReservasiMouseClicked

    private void btnUpdateStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateStatusActionPerformed
       String idText = lblDetailId.getText();
        if(idText.isEmpty() || idText.equals("(ID)")){
            JOptionPane.showMessageDialog(this, "Silakan pilih data reservasi dari tabel.");
            return;
        }
    
        int idReservasi = Integer.parseInt(idText);
        String statusBaru = comboUpdateStatus.getSelectedItem().toString();
        int confirm = JOptionPane.showConfirmDialog(this, "Ubah status reservasi ID " + idReservasi + " menjadi '" + statusBaru + "'?", "Konfirmasi Update", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            if(controller.updateStatus(idReservasi, statusBaru)){
                JOptionPane.showMessageDialog(this, "Status reservasi berhasil diupdate.");
                load_table();
                panelAksi.setVisible(false);
            }
        }
    }//GEN-LAST:event_btnUpdateStatusActionPerformed

    private void btnHapusReservasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusReservasiActionPerformed
        String idText = lblDetailId.getText();
        if(idText.isEmpty() || idText.equals("(ID)")){
            JOptionPane.showMessageDialog(this, "Silakan pilih data reservasi dari tabel.");
            return;
        }
        
        int idReservasi = Integer.parseInt(idText);
        int confirm = JOptionPane.showConfirmDialog(this, "Yakin ingin menghapus data reservasi ID " + idReservasi + "?\n(Status kamar terkait akan dikembalikan ke 'Tersedia')", "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            if(controller.deleteReservasi(idReservasi)){
                JOptionPane.showMessageDialog(this, "Data reservasi berhasil dihapus.");
                load_table();
                panelAksi.setVisible(false);
            }
        }
    }//GEN-LAST:event_btnHapusReservasiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataReservasiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataReservasiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataReservasiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataReservasiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataReservasiForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapusReservasi;
    private javax.swing.JButton btnUpdateStatus;
    private javax.swing.JComboBox<String> comboUpdateStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDetailId;
    private javax.swing.JLabel lblJudulUtama;
    private javax.swing.JPanel panelAksi;
    private javax.swing.JPanel panelJudul;
    private javax.swing.JTable tabelReservasi;
    // End of variables declaration//GEN-END:variables
}
