
package view;


import java.awt.Cursor;
import java.awt.Desktop;
import java.net.URI;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JOptionPane;
import model.User;

public class Home extends javax.swing.JFrame {

    private User currentUser;

    /**
     * Constructor untuk aplikasi saat pertama kali dibuka (mode belum login).
     */
    public Home() {
        initComponents();
        setupUI();
        setTampilanLoggedOut();
    }
    
    /**
     * Constructor untuk user yang sudah berhasil login.
     */
    public Home(User user) {
        initComponents();
        this.currentUser = user;
        setupUI();
        setTampilanLoggedIn(user);
    }
    
    /**
     * Method terpusat untuk semua pengaturan UI awal.
     */
    private void setupUI() {
        this.setLocationRelativeTo(null);
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        
        // Atur kursor untuk komponen yang bisa diklik
        lbla1.setCursor(new Cursor(Cursor.HAND_CURSOR));
        lbla2.setCursor(new Cursor(Cursor.HAND_CURSOR));
        lbla7.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnPesan.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnMasuk.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnLogout.setCursor(new Cursor(Cursor.HAND_CURSOR));
        
        // Mengisi pilihan bahasa dan mengatur bahasa default
        comboBahasa.removeAllItems();
        comboBahasa.addItem("Bahasa Indonesia");
        comboBahasa.addItem("English");
        ubahBahasa("in", "ID"); // Set bahasa default
    }

    
    private void setTampilanLoggedIn(User user) {
        this.currentUser = user;
        this.btnMasuk.setVisible(false);
        this.lblSalamPengguna.setText("Halo, " + currentUser.getNamaLengkap());
        this.lblSalamPengguna.setVisible(true);
        this.btnLogout.setVisible(true);
        this.btnPesan.setEnabled(true);
        this.lbla2.setEnabled(true);
    }

    /**
     * Mengubah UI ke mode BELUM LOGIN.
     */
    private void setTampilanLoggedOut() {
        this.currentUser = null;
        this.btnMasuk.setVisible(true);
        this.lblSalamPengguna.setVisible(false);
        this.btnLogout.setVisible(false);
        this.btnPesan.setEnabled(false);
        this.lbla2.setEnabled(false);
    }

    private void ubahBahasa(String kodeBahasa, String kodeNegara) {
        try {
            Locale locale = new Locale(kodeBahasa, kodeNegara);
            ResourceBundle messages = ResourceBundle.getBundle("i18n.messages", locale);
            
            lblJudul.setText(messages.getString("welcome.title"));
            lblSubJudul.setText(messages.getString("welcome.subtitle"));
            lblLUXURYHOTELEXPERIENCE.setText(messages.getString("welcome.s"));
            lbl4.setText(messages.getString("welcome.s4"));
            btnPesan.setText(messages.getString("welcome.button.book"));
            
            lbla1.setText(messages.getString("welcome.a1"));
            lbla2.setText(messages.getString("welcome.a2"));
            lbla3.setText(messages.getString("welcome.a3"));
            lbla4.setText(messages.getString("welcome.a4"));
            lbla5.setText(messages.getString("welcome.a5"));
            lbla6.setText(messages.getString("welcome.a6"));
            lbla7.setText(messages.getString("welcome.a7"));
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat file bahasa: " + e.getMessage());
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblJudul = new javax.swing.JLabel();
        lblSubJudul = new javax.swing.JLabel();
        lblLUXURYHOTELEXPERIENCE = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();
        btnPesan = new javax.swing.JButton();
        lbla1 = new javax.swing.JLabel();
        lbla7 = new javax.swing.JLabel();
        lbla3 = new javax.swing.JLabel();
        lbla2 = new javax.swing.JLabel();
        lbla4 = new javax.swing.JLabel();
        lbla5 = new javax.swing.JLabel();
        lbla6 = new javax.swing.JLabel();
        comboBahasa = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        btnMasuk = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        lblSalamPengguna = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1540, 840));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblJudul.setFont(new java.awt.Font("Segoe UI", 1, 42)); // NOI18N
        lblJudul.setForeground(new java.awt.Color(255, 255, 255));
        lblJudul.setText("A UNIQUE EXPERIENCE");
        jPanel1.add(lblJudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 760, -1));

        lblSubJudul.setFont(new java.awt.Font("Segoe UI", 1, 42)); // NOI18N
        lblSubJudul.setForeground(new java.awt.Color(255, 255, 255));
        lblSubJudul.setText("Where To Stay");
        jPanel1.add(lblSubJudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, 470, -1));

        lblLUXURYHOTELEXPERIENCE.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblLUXURYHOTELEXPERIENCE.setForeground(new java.awt.Color(255, 204, 102));
        lblLUXURYHOTELEXPERIENCE.setText("L u x u r y  H o t e l  E x p e r i e n c e");
        jPanel1.add(lblLUXURYHOTELEXPERIENCE, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, -1, -1));

        lbl4.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lbl4.setForeground(new java.awt.Color(255, 51, 51));
        lbl4.setText("G e t  S p e c i a l  D e a l s   F o r   D i r e c t   B o o k i n g !");
        jPanel1.add(lbl4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 490, 610, -1));

        btnPesan.setBackground(new java.awt.Color(217, 160, 24));
        btnPesan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnPesan.setForeground(new java.awt.Color(255, 255, 255));
        btnPesan.setText("Book Now");
        btnPesan.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 25, 10, 25));
        btnPesan.setFocusable(false);
        btnPesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesanActionPerformed(evt);
            }
        });
        jPanel1.add(btnPesan, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 540, -1, -1));

        lbla1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbla1.setForeground(new java.awt.Color(255, 255, 255));
        lbla1.setText("Home");
        lbla1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbla1MouseClicked(evt);
            }
        });
        jPanel1.add(lbla1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, -1, -1));

        lbla7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbla7.setForeground(new java.awt.Color(255, 255, 255));
        lbla7.setText("Contact");
        lbla7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbla7MouseClicked(evt);
            }
        });
        jPanel1.add(lbla7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 90, -1, -1));

        lbla3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbla3.setForeground(new java.awt.Color(255, 255, 255));
        lbla3.setText("Restaurant");
        jPanel1.add(lbla3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 90, -1, -1));

        lbla2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbla2.setForeground(new java.awt.Color(255, 255, 255));
        lbla2.setText("Rooms");
        lbla2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbla2MouseClicked(evt);
            }
        });
        jPanel1.add(lbla2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 90, -1, -1));

        lbla4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbla4.setForeground(new java.awt.Color(255, 255, 255));
        lbla4.setText("Facilities");
        jPanel1.add(lbla4, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 90, -1, -1));

        lbla5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbla5.setForeground(new java.awt.Color(255, 255, 255));
        lbla5.setText("Promotion");
        jPanel1.add(lbla5, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 90, -1, -1));

        lbla6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbla6.setForeground(new java.awt.Color(255, 255, 255));
        lbla6.setText("Activity & Gallery");
        jPanel1.add(lbla6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 90, -1, -1));

        comboBahasa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboBahasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBahasaActionPerformed(evt);
            }
        });
        jPanel1.add(comboBahasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 90, -1, -1));

        jLabel2.setBackground(new java.awt.Color(0, 204, 51));
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Documents\\java\\icons8-whatsapp-64.png")); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1430, 760, 70, 50));

        btnMasuk.setText("Login");
        btnMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasukActionPerformed(evt);
            }
        });
        jPanel1.add(btnMasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 140, -1, -1));

        btnLogout.setText("jButton1");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 180, -1, -1));

        lblSalamPengguna.setForeground(new java.awt.Color(255, 255, 255));
        lblSalamPengguna.setText("jLabel3");
        jPanel1.add(lblSalamPengguna, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 180, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\Jun 18, 2025, 12_59_46 AM.png")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1540, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 1024));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboBahasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBahasaActionPerformed
      if (comboBahasa.getSelectedItem() == null) {
            return;
        }
        String pilihan = comboBahasa.getSelectedItem().toString();
        if (pilihan.equals("English")) {
            ubahBahasa("en", "US");
        } else {
            ubahBahasa("in", "ID");
        }
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            // Panggil method khusus saat label diklik
            openWhatsApp();
        }
    });
    }
        
        private void openWhatsApp() {
    try {
        // Ganti dengan nomor WhatsApp tujuan Anda (gunakan format internasional tanpa "+")
        String nomorWhatsApp = "6281316056818"; // Contoh: nomor Indonesia 0812...
        String url = "https://wa.me/" + nomorWhatsApp;

        // Cek apakah fitur Desktop didukung oleh sistem
        if (Desktop.isDesktopSupported()) {
            // Buka browser default dengan URL WhatsApp
            Desktop.getDesktop().browse(new URI(url));
        } else {
            JOptionPane.showMessageDialog(this, "Fitur ini tidak didukung di sistem Anda.");
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal membuka WhatsApp: " + e.getMessage());
        e.printStackTrace();
    }
    
            
    }//GEN-LAST:event_comboBahasaActionPerformed

    private void lbla1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbla1MouseClicked
         
    }//GEN-LAST:event_lbla1MouseClicked

    private void lbla7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbla7MouseClicked
       new Contact(this.currentUser).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbla7MouseClicked

    private void btnPesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesanActionPerformed
        new UserDashboardForm(this.currentUser).setVisible(true);
        this.dispose();
       
    }//GEN-LAST:event_btnPesanActionPerformed

    private void lbla2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbla2MouseClicked
         new UserDashboardForm(this.currentUser).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbla2MouseClicked

    private void btnMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasukActionPerformed
           LoginDialog dialog = new LoginDialog(this, true);
        dialog.setVisible(true);
        User user = dialog.getAuthenticatedUser();
        
        if (user != null) {
            if ("Admin".equals(user.getRole())) {
                new AdminDashboardForm().setVisible(true);
                this.dispose();
            } else {
                this.currentUser = user; 
                setTampilanLoggedIn(user);
            }
        }
    }//GEN-LAST:event_btnMasukActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this, "Yakin ingin logout?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            setTampilanLoggedOut();
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnMasuk;
    private javax.swing.JButton btnPesan;
    private javax.swing.JComboBox<String> comboBahasa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JLabel lblLUXURYHOTELEXPERIENCE;
    private javax.swing.JLabel lblSalamPengguna;
    private javax.swing.JLabel lblSubJudul;
    private javax.swing.JLabel lbla1;
    private javax.swing.JLabel lbla2;
    private javax.swing.JLabel lbla3;
    private javax.swing.JLabel lbla4;
    private javax.swing.JLabel lbla5;
    private javax.swing.JLabel lbla6;
    private javax.swing.JLabel lbla7;
    // End of variables declaration//GEN-END:variables
}
