/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;


import db.Koneksi;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class ManajemenTipeKamarForm extends javax.swing.JFrame {

    private File fileGambarTerpilih; // Variabel untuk menyimpan file gambar

    public ManajemenTipeKamarForm() {
        initComponents();
        // Styling header tabel
        tabelTipeKamar.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 14));
        tabelTipeKamar.getTableHeader().setBackground(new Color(0, 51, 102));
        tabelTipeKamar.getTableHeader().setForeground(new Color(255, 255, 255));
    
        load_table();
        clear_form();
    }
    
    // Method untuk memuat data ke tabel
    private void load_table() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("Nama Tipe");
        model.addColumn("Fasilitas");
        model.addColumn("Harga per Malam");
        model.addColumn("File Gambar"); // Tambah kolom untuk nama file gambar

        try {
            String sql = "SELECT id, nama_tipe, fasilitas, harga, gambar FROM tipe_kamar ORDER BY id ASC";
            Connection conn = (Connection) Koneksi.configDB();
            Statement stm = conn.createStatement();
            ResultSet res = stm.executeQuery(sql);
            while (res.next()) {
                model.addRow(new Object[]{
                    res.getString("id"), 
                    res.getString("nama_tipe"), 
                    res.getString("fasilitas"), 
                    "Rp " + res.getString("harga"),
                    res.getString("gambar") // Tampilkan nama file gambar
                });
            }
            tabelTipeKamar.setModel(model);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat tabel: " + e.getMessage());
        }
    }

    // Method untuk membersihkan form input
    private void clear_form() {
        lblIdTipeKamar.setText("0");
        txtNamaTipe.setText("");
        txtAreaFasilitas.setText("");
        txtHarga.setText("");
        lblPreviewGambar.setIcon(null); // Bersihkan preview gambar
        lblPreviewGambar.setText("Preview Gambar");
        fileGambarTerpilih = null; // Reset file yang dipilih
    }

    // Method bantuan untuk menampilkan gambar di JLabel
    private void displayImage(String namaFileGambar) {
        if (namaFileGambar == null || namaFileGambar.isEmpty()) {
            lblPreviewGambar.setIcon(null);
            lblPreviewGambar.setText("Tidak ada gambar");
            return;
        }
        try {
            String pathGambar = System.getProperty("user.dir") + "/app_images/" + namaFileGambar;
            ImageIcon icon = new ImageIcon(pathGambar);
            Image img = icon.getImage().getScaledInstance(lblPreviewGambar.getWidth(), lblPreviewGambar.getHeight(), Image.SCALE_SMOOTH);
            lblPreviewGambar.setIcon(new ImageIcon(img));
        } catch (Exception e) {
            lblPreviewGambar.setIcon(null);
            lblPreviewGambar.setText("Gagal muat gambar");
            System.err.println("Error memuat gambar: " + e.getMessage());
        }
    }




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblJudulUtama = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNamaTipe = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaFasilitas = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        txtHarga = new javax.swing.JTextField();
        btnSimpanTipe = new javax.swing.JButton();
        btnEditTipe = new javax.swing.JButton();
        btnHapusTipe = new javax.swing.JButton();
        btnBersihTipe = new javax.swing.JButton();
        lblIdTipeKamar = new javax.swing.JLabel();
        lblPreviewGambar = new javax.swing.JLabel();
        btnPilihGambar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelTipeKamar = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Manajemen Tipe Kamar - Hotel Surya Indah Salatiga");

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        lblJudulUtama.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        lblJudulUtama.setForeground(new java.awt.Color(255, 255, 255));
        lblJudulUtama.setText("Manajemen Tipe Kamar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblJudulUtama, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1255, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblJudulUtama)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Nama Tipe:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Fasilitas :");

        txtAreaFasilitas.setColumns(20);
        txtAreaFasilitas.setRows(5);
        jScrollPane1.setViewportView(txtAreaFasilitas);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Harga Per Malam :");

        btnSimpanTipe.setBackground(new java.awt.Color(0, 123, 255));
        btnSimpanTipe.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSimpanTipe.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpanTipe.setText("Simpan");
        btnSimpanTipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanTipeActionPerformed(evt);
            }
        });

        btnEditTipe.setBackground(new java.awt.Color(222, 226, 230));
        btnEditTipe.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEditTipe.setText("Edit");
        btnEditTipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditTipeActionPerformed(evt);
            }
        });

        btnHapusTipe.setBackground(new java.awt.Color(222, 226, 230));
        btnHapusTipe.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHapusTipe.setText("Hapus");
        btnHapusTipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusTipeActionPerformed(evt);
            }
        });

        btnBersihTipe.setBackground(new java.awt.Color(222, 226, 230));
        btnBersihTipe.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBersihTipe.setText("Bersihkan");
        btnBersihTipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBersihTipeActionPerformed(evt);
            }
        });

        lblIdTipeKamar.setText("0");

        btnPilihGambar.setText("Pilih Gambar");
        btnPilihGambar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPilihGambarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNamaTipe, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtHarga, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnEditTipe, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(61, 61, 61)
                                .addComponent(btnHapusTipe, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnBersihTipe, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnSimpanTipe, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(110, 110, 110))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(149, 149, 149)
                                .addComponent(btnPilihGambar)
                                .addGap(18, 18, 18)
                                .addComponent(lblPreviewGambar, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblIdTipeKamar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(lblIdTipeKamar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNamaTipe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(btnSimpanTipe)
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditTipe)
                    .addComponent(btnHapusTipe)
                    .addComponent(btnBersihTipe))
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPreviewGambar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPilihGambar))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        tabelTipeKamar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tabelTipeKamar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelTipeKamar.setSelectionBackground(new java.awt.Color(0, 123, 255));
        tabelTipeKamar.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tabelTipeKamar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelTipeKamarMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelTipeKamar);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 777, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(172, 172, 172))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanTipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanTipeActionPerformed
           String namaFileGambar = null; // Defaultnya null (tidak ada gambar)

        // 1. Proses dan salin gambar jika ada file yang dipilih oleh admin
        if (fileGambarTerpilih != null) {
            try {
                String folderTujuan = System.getProperty("user.dir") + "/app_images/";
                File folder = new File(folderTujuan);
                if (!folder.exists()) {
                    folder.mkdirs(); // Buat folder jika belum ada
                }

                // Buat nama file baru yang unik untuk menghindari nama yang sama
                String ekstensi = fileGambarTerpilih.getName().substring(fileGambarTerpilih.getName().lastIndexOf("."));
                namaFileGambar = "kamar_" + System.currentTimeMillis() + ekstensi;

                // Salin file
                java.nio.file.Files.copy(fileGambarTerpilih.toPath(), 
                        java.nio.file.Paths.get(folderTujuan + namaFileGambar), 
                        java.nio.file.StandardCopyOption.REPLACE_EXISTING);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Gagal menyimpan file gambar: " + e.getMessage());
                return; // Hentikan proses jika gagal menyimpan gambar
            }
        }

        // 2. Simpan semua data ke database
        try {
            String sql = "INSERT INTO tipe_kamar (nama_tipe, fasilitas, harga, gambar) VALUES (?, ?, ?, ?)";
            Connection conn = (Connection) Koneksi.configDB();
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, txtNamaTipe.getText());
            pst.setString(2, txtAreaFasilitas.getText());
            pst.setString(3, txtHarga.getText());
            pst.setString(4, namaFileGambar); // Simpan nama file (atau null jika tidak ada)
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data Tipe Kamar Berhasil Disimpan");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal menyimpan data ke DB: " + e.getMessage());
        }

        load_table();
        clear_form();
    }//GEN-LAST:event_btnSimpanTipeActionPerformed

    private void btnEditTipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditTipeActionPerformed
       String namaFileGambar = null;
        
        // Cek apakah admin memilih gambar baru untuk diedit
        if (fileGambarTerpilih != null) {
            // Logika menyalin file sama seperti saat simpan
            try {
                String folderTujuan = System.getProperty("user.dir") + "/app_images/";
                File folder = new File(folderTujuan);
                if (!folder.exists()) folder.mkdirs();

                String ekstensi = fileGambarTerpilih.getName().substring(fileGambarTerpilih.getName().lastIndexOf("."));
                namaFileGambar = "kamar_" + System.currentTimeMillis() + ekstensi;
                
                java.nio.file.Files.copy(fileGambarTerpilih.toPath(), 
                        java.nio.file.Paths.get(folderTujuan + namaFileGambar), 
                        java.nio.file.StandardCopyOption.REPLACE_EXISTING);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Gagal menyimpan file gambar baru: " + e.getMessage());
                return;
            }
        }

        try {
            String sql;
            // Jika ada gambar baru, update juga kolom gambar. Jika tidak, jangan update kolom gambar.
            if (namaFileGambar != null) {
                sql = "UPDATE tipe_kamar SET nama_tipe = ?, fasilitas = ?, harga = ?, gambar = ? WHERE id = ?";
            } else {
                sql = "UPDATE tipe_kamar SET nama_tipe = ?, fasilitas = ?, harga = ? WHERE id = ?";
            }
            
            Connection conn = (Connection) Koneksi.configDB();
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, txtNamaTipe.getText());
            pst.setString(2, txtAreaFasilitas.getText());
            pst.setString(3, txtHarga.getText());
            
            if (namaFileGambar != null) {
                pst.setString(4, namaFileGambar);
                pst.setString(5, lblIdTipeKamar.getText());
            } else {
                pst.setString(4, lblIdTipeKamar.getText());
            }

            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil Diedit");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal mengedit data: " + e.getMessage());
        }
        load_table();
        clear_form();
    
    }//GEN-LAST:event_btnEditTipeActionPerformed

    private void btnHapusTipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusTipeActionPerformed
        try {
            int confirm = JOptionPane.showConfirmDialog(this, "Yakin ingin menghapus data tipe kamar ini?", "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                String sql = "DELETE FROM tipe_kamar WHERE id = ?";
                Connection conn = (Connection) Koneksi.configDB();
                PreparedStatement pst = conn.prepareStatement(sql);
                pst.setString(1, lblIdTipeKamar.getText());
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal menghapus data: " + e.getMessage());
        }
        load_table();
        clear_form();
    }//GEN-LAST:event_btnHapusTipeActionPerformed

    private void btnBersihTipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBersihTipeActionPerformed
        clear_form();
    }//GEN-LAST:event_btnBersihTipeActionPerformed

    private void tabelTipeKamarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelTipeKamarMouseClicked
         int baris = tabelTipeKamar.getSelectedRow();
        
        lblIdTipeKamar.setText(tabelTipeKamar.getValueAt(baris, 0).toString());
        txtNamaTipe.setText(tabelTipeKamar.getValueAt(baris, 1).toString());
        txtAreaFasilitas.setText(tabelTipeKamar.getValueAt(baris, 2).toString());
        
        String harga = tabelTipeKamar.getValueAt(baris, 3).toString().replace("Rp ", "");
        txtHarga.setText(harga);

        // Ambil nama file gambar dari tabel dan tampilkan preview-nya
        Object namaFileObj = tabelTipeKamar.getValueAt(baris, 4);
        String namaFileGambar = (namaFileObj == null) ? null : namaFileObj.toString();
        displayImage(namaFileGambar);
        
        fileGambarTerpilih = null; // Reset pilihan file saat memilih dari tabel
    

    }//GEN-LAST:event_tabelTipeKamarMouseClicked

    private void btnPilihGambarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPilihGambarActionPerformed
        JFileChooser fileChooser = new JFileChooser();
    // Filter agar hanya file gambar yang bisa dipilih
    fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Image Files", "jpg", "png", "gif", "jpeg"));
    
    int result = fileChooser.showOpenDialog(this);
    if (result == JFileChooser.APPROVE_OPTION) {
        // Simpan file yang dipilih ke variabel global
        fileGambarTerpilih = fileChooser.getSelectedFile();
        
        // Tampilkan preview gambar di JLabel
        try {
            ImageIcon icon = new ImageIcon(fileGambarTerpilih.getAbsolutePath());
            Image img = icon.getImage().getScaledInstance(lblPreviewGambar.getWidth(), lblPreviewGambar.getHeight(), Image.SCALE_SMOOTH);
            lblPreviewGambar.setIcon(new ImageIcon(img));
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal memuat preview gambar.");
        }
    }
    }//GEN-LAST:event_btnPilihGambarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManajemenTipeKamarForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManajemenTipeKamarForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManajemenTipeKamarForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManajemenTipeKamarForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManajemenTipeKamarForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBersihTipe;
    private javax.swing.JButton btnEditTipe;
    private javax.swing.JButton btnHapusTipe;
    private javax.swing.JButton btnPilihGambar;
    private javax.swing.JButton btnSimpanTipe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblIdTipeKamar;
    private javax.swing.JLabel lblJudulUtama;
    private javax.swing.JLabel lblPreviewGambar;
    private javax.swing.JTable tabelTipeKamar;
    private javax.swing.JTextArea txtAreaFasilitas;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtNamaTipe;
    // End of variables declaration//GEN-END:variables
}
